version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: '7.4.x-webserver'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    links: 
      - postgresql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  postgresql:
    build:
      context: "./bin/${DATABASE}"
    container_name: 'postgresql-13'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_POSTGRESQL_PORT}:5432"
    volumes: 
      - ${POSTGRES_DATA_DIR-./data/postgresql}:/var/lib/postgresql/data
      - ${POSTGRES_LOG_DIR-./logs/postgresql}:/var/log/postgresql
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
  redis:
    container_name: 'sc-redis'
    image: redis:latest
    ports:
      - "${HOST_MACHINE_REDIS_PORT}:6379"
